// Build-time configuration - Generated by CI/CD
class BuildConfig {
  static const String supabaseUrl = 'PLACEHOLDER_SUPABASE_URL';
  static const String supabaseAnonKey = 'PLACEHOLDER_SUPABASE_ANON_KEY';
  static const String appName = 'GitHub Radar News';
  static const String appVersion = '1.0.5';
  
  static bool get hasValidConfig =>
      supabaseUrl != 'PLACEHOLDER_SUPABASE_URL' &&
      supabaseAnonKey != 'PLACEHOLDER_SUPABASE_ANON_KEY' &&
      supabaseUrl.isNotEmpty &&
      supabaseAnonKey.isNotEmpty;
}