name: Analyze Missing Repositories

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      limit:
        description: 'Maximum number of repositories to analyze'
        required: false
        default: '10'
        type: string
      delay:
        description: 'Delay between analyses (ms)'
        required: false
        default: '5000'
        type: string

jobs:
  analyze-missing:
    name: Analyze Missing Repositories
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: cli/package-lock.json
        
    - name: Install CLI dependencies
      working-directory: cli
      run: npm ci
      
    - name: Build CLI
      working-directory: cli
      run: npm run build
      
    - name: Run analyze-missing command
      working-directory: cli
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        # Use inputs if manually triggered, otherwise use defaults
        LIMIT="${{ github.event.inputs.limit || '10' }}"
        DELAY="${{ github.event.inputs.delay || '5000' }}"
        
        echo "🔍 Starting analyze-missing with limit=${LIMIT} delay=${DELAY}"
        node dist/index.js analyze-missing --limit "${LIMIT}" --delay "${DELAY}"
        
    - name: Upload analysis logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: analysis-logs-${{ github.run_number }}
        path: |
          cli/logs/
          cli/reports/
        retention-days: 7