name: Analyze Missing Repositories (Hourly)

on:
  # Run every hour
  schedule:
    - cron: '0 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      limit:
        description: 'Maximum number of repositories to analyze'
        required: false
        default: '20'
        type: string
      delay:
        description: 'Delay between analyses (ms)'
        required: false
        default: '3000'
        type: string

jobs:
  analyze-missing:
    name: Analyze Missing Repositories
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: cli/package-lock.json
        
    - name: Install CLI dependencies
      working-directory: cli
      run: npm ci
      
    - name: Build CLI
      working-directory: cli
      run: npm run build
      
    - name: Run analyze-missing command
      working-directory: cli
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        # Use inputs if manually triggered, otherwise use medium defaults (20 repos, 3s delay)
        LIMIT="${{ github.event.inputs.limit || '20' }}"
        DELAY="${{ github.event.inputs.delay || '3000' }}"
        
        echo "🔍 Starting analyze-missing:medium equivalent with limit=${LIMIT} delay=${DELAY}"
        echo "⏰ Started at: $(date)"
        
        node dist/index.js analyze-missing --limit "${LIMIT}" --delay "${DELAY}"
        
        echo "✅ Analysis completed at: $(date)"
        
    - name: Upload analysis logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: analysis-logs-${{ github.run_number }}
        path: |
          cli/logs/
          cli/reports/
        retention-days: 7